//
// Autogenerated by Thrift Compiler (0.13.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');

var Types_ttypes = require('./Types_types');


var ttypes = require('./ResponseDataService_types');
//HELPER FUNCTIONS AND STRUCTURES

var ResponseService_NewFindingAvailable_args = function(args) {
};
ResponseService_NewFindingAvailable_args.prototype = {};
ResponseService_NewFindingAvailable_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ResponseService_NewFindingAvailable_args.prototype.write = function(output) {
  output.writeStructBegin('ResponseService_NewFindingAvailable_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ResponseService_NewFindingAvailable_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
ResponseService_NewFindingAvailable_result.prototype = {};
ResponseService_NewFindingAvailable_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ResponseService_NewFindingAvailable_result.prototype.write = function(output) {
  output.writeStructBegin('ResponseService_NewFindingAvailable_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ResponseService_RequestFinding_args = function(args) {
  this.userId = null;
  if (args) {
    if (args.userId !== undefined && args.userId !== null) {
      this.userId = args.userId;
    }
  }
};
ResponseService_RequestFinding_args.prototype = {};
ResponseService_RequestFinding_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.userId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ResponseService_RequestFinding_args.prototype.write = function(output) {
  output.writeStructBegin('ResponseService_RequestFinding_args');
  if (this.userId !== null && this.userId !== undefined) {
    output.writeFieldBegin('userId', Thrift.Type.STRING, 1);
    output.writeString(this.userId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ResponseService_RequestFinding_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new Types_ttypes.UserResponseDataSet(args.success);
    }
  }
};
ResponseService_RequestFinding_result.prototype = {};
ResponseService_RequestFinding_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new Types_ttypes.UserResponseDataSet();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ResponseService_RequestFinding_result.prototype.write = function(output) {
  output.writeStructBegin('ResponseService_RequestFinding_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ResponseService_RequestFindingHistory_args = function(args) {
  this.userId = null;
  if (args) {
    if (args.userId !== undefined && args.userId !== null) {
      this.userId = args.userId;
    }
  }
};
ResponseService_RequestFindingHistory_args.prototype = {};
ResponseService_RequestFindingHistory_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.userId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ResponseService_RequestFindingHistory_args.prototype.write = function(output) {
  output.writeStructBegin('ResponseService_RequestFindingHistory_args');
  if (this.userId !== null && this.userId !== undefined) {
    output.writeFieldBegin('userId', Thrift.Type.STRING, 1);
    output.writeString(this.userId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ResponseService_RequestFindingHistory_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new Types_ttypes.UserHistoryDataSet(args.success);
    }
  }
};
ResponseService_RequestFindingHistory_result.prototype = {};
ResponseService_RequestFindingHistory_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new Types_ttypes.UserHistoryDataSet();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ResponseService_RequestFindingHistory_result.prototype.write = function(output) {
  output.writeStructBegin('ResponseService_RequestFindingHistory_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ResponseServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
ResponseServiceClient.prototype = {};
ResponseServiceClient.prototype.seqid = function() { return this._seqid; };
ResponseServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

ResponseServiceClient.prototype.NewFindingAvailable = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_NewFindingAvailable();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_NewFindingAvailable();
  }
};

ResponseServiceClient.prototype.send_NewFindingAvailable = function() {
  var output = new this.pClass(this.output);
  var args = new ResponseService_NewFindingAvailable_args();
  try {
    output.writeMessageBegin('NewFindingAvailable', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

ResponseServiceClient.prototype.recv_NewFindingAvailable = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ResponseService_NewFindingAvailable_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('NewFindingAvailable failed: unknown result');
};

ResponseServiceClient.prototype.RequestFinding = function(userId, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_RequestFinding(userId);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_RequestFinding(userId);
  }
};

ResponseServiceClient.prototype.send_RequestFinding = function(userId) {
  var output = new this.pClass(this.output);
  var params = {
    userId: userId
  };
  var args = new ResponseService_RequestFinding_args(params);
  try {
    output.writeMessageBegin('RequestFinding', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

ResponseServiceClient.prototype.recv_RequestFinding = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ResponseService_RequestFinding_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('RequestFinding failed: unknown result');
};

ResponseServiceClient.prototype.RequestFindingHistory = function(userId, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_RequestFindingHistory(userId);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_RequestFindingHistory(userId);
  }
};

ResponseServiceClient.prototype.send_RequestFindingHistory = function(userId) {
  var output = new this.pClass(this.output);
  var params = {
    userId: userId
  };
  var args = new ResponseService_RequestFindingHistory_args(params);
  try {
    output.writeMessageBegin('RequestFindingHistory', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

ResponseServiceClient.prototype.recv_RequestFindingHistory = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ResponseService_RequestFindingHistory_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('RequestFindingHistory failed: unknown result');
};
var ResponseServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
ResponseServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
ResponseServiceProcessor.prototype.process_NewFindingAvailable = function(seqid, input, output) {
  var args = new ResponseService_NewFindingAvailable_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.NewFindingAvailable.length === 0) {
    Q.fcall(this._handler.NewFindingAvailable.bind(this._handler)
    ).then(function(result) {
      var result_obj = new ResponseService_NewFindingAvailable_result({success: result});
      output.writeMessageBegin("NewFindingAvailable", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("NewFindingAvailable", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.NewFindingAvailable(function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new ResponseService_NewFindingAvailable_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("NewFindingAvailable", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("NewFindingAvailable", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
ResponseServiceProcessor.prototype.process_RequestFinding = function(seqid, input, output) {
  var args = new ResponseService_RequestFinding_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.RequestFinding.length === 1) {
    Q.fcall(this._handler.RequestFinding.bind(this._handler),
      args.userId
    ).then(function(result) {
      var result_obj = new ResponseService_RequestFinding_result({success: result});
      output.writeMessageBegin("RequestFinding", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("RequestFinding", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.RequestFinding(args.userId, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new ResponseService_RequestFinding_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("RequestFinding", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("RequestFinding", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
ResponseServiceProcessor.prototype.process_RequestFindingHistory = function(seqid, input, output) {
  var args = new ResponseService_RequestFindingHistory_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.RequestFindingHistory.length === 1) {
    Q.fcall(this._handler.RequestFindingHistory.bind(this._handler),
      args.userId
    ).then(function(result) {
      var result_obj = new ResponseService_RequestFindingHistory_result({success: result});
      output.writeMessageBegin("RequestFindingHistory", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("RequestFindingHistory", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.RequestFindingHistory(args.userId, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new ResponseService_RequestFindingHistory_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("RequestFindingHistory", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("RequestFindingHistory", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
