//
// Autogenerated by Thrift Compiler (0.13.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');

var Types_ttypes = require('./Types_types');


var ttypes = require('./SendSymptomeService_types');
//HELPER FUNCTIONS AND STRUCTURES

var SendSymptomeService_SendSymptomeDataSet_args = function(args) {
  this.data = null;
  if (args) {
    if (args.data !== undefined && args.data !== null) {
      this.data = new Types_ttypes.SymptomeInputData(args.data);
    }
  }
};
SendSymptomeService_SendSymptomeDataSet_args.prototype = {};
SendSymptomeService_SendSymptomeDataSet_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.data = new Types_ttypes.SymptomeInputData();
        this.data.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SendSymptomeService_SendSymptomeDataSet_args.prototype.write = function(output) {
  output.writeStructBegin('SendSymptomeService_SendSymptomeDataSet_args');
  if (this.data !== null && this.data !== undefined) {
    output.writeFieldBegin('data', Thrift.Type.STRUCT, 1);
    this.data.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SendSymptomeService_SendSymptomeDataSet_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new Types_ttypes.ServiceResponse(args.success);
    }
  }
};
SendSymptomeService_SendSymptomeDataSet_result.prototype = {};
SendSymptomeService_SendSymptomeDataSet_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new Types_ttypes.ServiceResponse();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SendSymptomeService_SendSymptomeDataSet_result.prototype.write = function(output) {
  output.writeStructBegin('SendSymptomeService_SendSymptomeDataSet_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SendSymptomeService_SendDiseaseDataSet_args = function(args) {
  this.data = null;
  if (args) {
    if (args.data !== undefined && args.data !== null) {
      this.data = new Types_ttypes.DiseaseDataSet(args.data);
    }
  }
};
SendSymptomeService_SendDiseaseDataSet_args.prototype = {};
SendSymptomeService_SendDiseaseDataSet_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.data = new Types_ttypes.DiseaseDataSet();
        this.data.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SendSymptomeService_SendDiseaseDataSet_args.prototype.write = function(output) {
  output.writeStructBegin('SendSymptomeService_SendDiseaseDataSet_args');
  if (this.data !== null && this.data !== undefined) {
    output.writeFieldBegin('data', Thrift.Type.STRUCT, 1);
    this.data.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SendSymptomeService_SendDiseaseDataSet_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new Types_ttypes.ServiceResponse(args.success);
    }
  }
};
SendSymptomeService_SendDiseaseDataSet_result.prototype = {};
SendSymptomeService_SendDiseaseDataSet_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new Types_ttypes.ServiceResponse();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SendSymptomeService_SendDiseaseDataSet_result.prototype.write = function(output) {
  output.writeStructBegin('SendSymptomeService_SendDiseaseDataSet_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SendSymptomeService_GetSymptomeTypes_args = function(args) {
};
SendSymptomeService_GetSymptomeTypes_args.prototype = {};
SendSymptomeService_GetSymptomeTypes_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SendSymptomeService_GetSymptomeTypes_args.prototype.write = function(output) {
  output.writeStructBegin('SendSymptomeService_GetSymptomeTypes_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SendSymptomeService_GetSymptomeTypes_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [Types_ttypes.SymptomeType]);
    }
  }
};
SendSymptomeService_GetSymptomeTypes_result.prototype = {};
SendSymptomeService_GetSymptomeTypes_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        this.success = [];
        var _rtmp31 = input.readListBegin();
        var _size0 = _rtmp31.size || 0;
        for (var _i2 = 0; _i2 < _size0; ++_i2) {
          var elem3 = null;
          elem3 = new Types_ttypes.SymptomeType();
          elem3.read(input);
          this.success.push(elem3);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SendSymptomeService_GetSymptomeTypes_result.prototype.write = function(output) {
  output.writeStructBegin('SendSymptomeService_GetSymptomeTypes_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter4 in this.success) {
      if (this.success.hasOwnProperty(iter4)) {
        iter4 = this.success[iter4];
        iter4.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SendSymptomeServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
SendSymptomeServiceClient.prototype = {};
SendSymptomeServiceClient.prototype.seqid = function() { return this._seqid; };
SendSymptomeServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

SendSymptomeServiceClient.prototype.SendSymptomeDataSet = function(data, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_SendSymptomeDataSet(data);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_SendSymptomeDataSet(data);
  }
};

SendSymptomeServiceClient.prototype.send_SendSymptomeDataSet = function(data) {
  var output = new this.pClass(this.output);
  var params = {
    data: data
  };
  var args = new SendSymptomeService_SendSymptomeDataSet_args(params);
  try {
    output.writeMessageBegin('SendSymptomeDataSet', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

SendSymptomeServiceClient.prototype.recv_SendSymptomeDataSet = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SendSymptomeService_SendSymptomeDataSet_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('SendSymptomeDataSet failed: unknown result');
};

SendSymptomeServiceClient.prototype.SendDiseaseDataSet = function(data, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_SendDiseaseDataSet(data);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_SendDiseaseDataSet(data);
  }
};

SendSymptomeServiceClient.prototype.send_SendDiseaseDataSet = function(data) {
  var output = new this.pClass(this.output);
  var params = {
    data: data
  };
  var args = new SendSymptomeService_SendDiseaseDataSet_args(params);
  try {
    output.writeMessageBegin('SendDiseaseDataSet', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

SendSymptomeServiceClient.prototype.recv_SendDiseaseDataSet = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SendSymptomeService_SendDiseaseDataSet_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('SendDiseaseDataSet failed: unknown result');
};

SendSymptomeServiceClient.prototype.GetSymptomeTypes = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_GetSymptomeTypes();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_GetSymptomeTypes();
  }
};

SendSymptomeServiceClient.prototype.send_GetSymptomeTypes = function() {
  var output = new this.pClass(this.output);
  var args = new SendSymptomeService_GetSymptomeTypes_args();
  try {
    output.writeMessageBegin('GetSymptomeTypes', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

SendSymptomeServiceClient.prototype.recv_GetSymptomeTypes = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SendSymptomeService_GetSymptomeTypes_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('GetSymptomeTypes failed: unknown result');
};
var SendSymptomeServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
SendSymptomeServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
SendSymptomeServiceProcessor.prototype.process_SendSymptomeDataSet = function(seqid, input, output) {
  var args = new SendSymptomeService_SendSymptomeDataSet_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.SendSymptomeDataSet.length === 1) {
    Q.fcall(this._handler.SendSymptomeDataSet.bind(this._handler),
      args.data
    ).then(function(result) {
      var result_obj = new SendSymptomeService_SendSymptomeDataSet_result({success: result});
      output.writeMessageBegin("SendSymptomeDataSet", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("SendSymptomeDataSet", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.SendSymptomeDataSet(args.data, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new SendSymptomeService_SendSymptomeDataSet_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("SendSymptomeDataSet", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("SendSymptomeDataSet", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
SendSymptomeServiceProcessor.prototype.process_SendDiseaseDataSet = function(seqid, input, output) {
  var args = new SendSymptomeService_SendDiseaseDataSet_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.SendDiseaseDataSet.length === 1) {
    Q.fcall(this._handler.SendDiseaseDataSet.bind(this._handler),
      args.data
    ).then(function(result) {
      var result_obj = new SendSymptomeService_SendDiseaseDataSet_result({success: result});
      output.writeMessageBegin("SendDiseaseDataSet", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("SendDiseaseDataSet", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.SendDiseaseDataSet(args.data, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new SendSymptomeService_SendDiseaseDataSet_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("SendDiseaseDataSet", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("SendDiseaseDataSet", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
SendSymptomeServiceProcessor.prototype.process_GetSymptomeTypes = function(seqid, input, output) {
  var args = new SendSymptomeService_GetSymptomeTypes_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.GetSymptomeTypes.length === 0) {
    Q.fcall(this._handler.GetSymptomeTypes.bind(this._handler)
    ).then(function(result) {
      var result_obj = new SendSymptomeService_GetSymptomeTypes_result({success: result});
      output.writeMessageBegin("GetSymptomeTypes", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("GetSymptomeTypes", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.GetSymptomeTypes(function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new SendSymptomeService_GetSymptomeTypes_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("GetSymptomeTypes", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("GetSymptomeTypes", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
