/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace vdivsvirus.interfaces
{
  /// <summary>
  /// Symptome Strength
  /// 
  /// wenn Class: bool
  /// none - Kein Symptom
  /// yes - Habe Symptom
  /// 
  /// wenn Class: scalar
  /// 0 - kein Symptom
  /// 1 - sehr schwach
  /// 2 - schwach
  /// 3 - mittel
  /// 4 - stark
  /// 5 - sehr stark
  /// </summary>
  public enum SymptomeStrength
  {
    none = 0,
    yes = 1,
    weak = 2,
    middle = 3,
    strong = 4,
    verystrong = 5,
  }
}
