/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


namespace vdivsvirus.interfaces
{

  /// <summary>
  /// Structs of UserHistoryDataSet
  /// </summary>
  public partial class UserHistoryDataSet : TBase
  {
    private string _userID;
    private Dictionary<long, PropabilityDataSet> _history;
    private Dictionary<string, DiseaseType> _diseaseTypes;
    private string _message;

    public string UserID
    {
      get
      {
        return _userID;
      }
      set
      {
        __isset.userID = true;
        this._userID = value;
      }
    }

    public Dictionary<long, PropabilityDataSet> History
    {
      get
      {
        return _history;
      }
      set
      {
        __isset.history = true;
        this._history = value;
      }
    }

    public Dictionary<string, DiseaseType> DiseaseTypes
    {
      get
      {
        return _diseaseTypes;
      }
      set
      {
        __isset.diseaseTypes = true;
        this._diseaseTypes = value;
      }
    }

    public string Message
    {
      get
      {
        return _message;
      }
      set
      {
        __isset.message = true;
        this._message = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool userID;
      public bool history;
      public bool diseaseTypes;
      public bool message;
    }

    public UserHistoryDataSet()
    {
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                UserID = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Map)
              {
                {
                  TMap _map27 = await iprot.ReadMapBeginAsync(cancellationToken);
                  History = new Dictionary<long, PropabilityDataSet>(_map27.Count);
                  for(int _i28 = 0; _i28 < _map27.Count; ++_i28)
                  {
                    long _key29;
                    PropabilityDataSet _val30;
                    _key29 = await iprot.ReadI64Async(cancellationToken);
                    _val30 = new PropabilityDataSet();
                    await _val30.ReadAsync(iprot, cancellationToken);
                    History[_key29] = _val30;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.Map)
              {
                {
                  TMap _map31 = await iprot.ReadMapBeginAsync(cancellationToken);
                  DiseaseTypes = new Dictionary<string, DiseaseType>(_map31.Count);
                  for(int _i32 = 0; _i32 < _map31.Count; ++_i32)
                  {
                    string _key33;
                    DiseaseType _val34;
                    _key33 = await iprot.ReadStringAsync(cancellationToken);
                    _val34 = new DiseaseType();
                    await _val34.ReadAsync(iprot, cancellationToken);
                    DiseaseTypes[_key33] = _val34;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.String)
              {
                Message = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("UserHistoryDataSet");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if (UserID != null && __isset.userID)
        {
          field.Name = "userID";
          field.Type = TType.String;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(UserID, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (History != null && __isset.history)
        {
          field.Name = "history";
          field.Type = TType.Map;
          field.ID = 2;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          {
            await oprot.WriteMapBeginAsync(new TMap(TType.I64, TType.Struct, History.Count), cancellationToken);
            foreach (long _iter35 in History.Keys)
            {
              await oprot.WriteI64Async(_iter35, cancellationToken);
              await History[_iter35].WriteAsync(oprot, cancellationToken);
            }
            await oprot.WriteMapEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (DiseaseTypes != null && __isset.diseaseTypes)
        {
          field.Name = "diseaseTypes";
          field.Type = TType.Map;
          field.ID = 3;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          {
            await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.Struct, DiseaseTypes.Count), cancellationToken);
            foreach (string _iter36 in DiseaseTypes.Keys)
            {
              await oprot.WriteStringAsync(_iter36, cancellationToken);
              await DiseaseTypes[_iter36].WriteAsync(oprot, cancellationToken);
            }
            await oprot.WriteMapEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (Message != null && __isset.message)
        {
          field.Name = "message";
          field.Type = TType.String;
          field.ID = 4;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(Message, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      var other = that as UserHistoryDataSet;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.userID == other.__isset.userID) && ((!__isset.userID) || (System.Object.Equals(UserID, other.UserID))))
        && ((__isset.history == other.__isset.history) && ((!__isset.history) || (TCollections.Equals(History, other.History))))
        && ((__isset.diseaseTypes == other.__isset.diseaseTypes) && ((!__isset.diseaseTypes) || (TCollections.Equals(DiseaseTypes, other.DiseaseTypes))))
        && ((__isset.message == other.__isset.message) && ((!__isset.message) || (System.Object.Equals(Message, other.Message))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.userID)
          hashcode = (hashcode * 397) + UserID.GetHashCode();
        if(__isset.history)
          hashcode = (hashcode * 397) + TCollections.GetHashCode(History);
        if(__isset.diseaseTypes)
          hashcode = (hashcode * 397) + TCollections.GetHashCode(DiseaseTypes);
        if(__isset.message)
          hashcode = (hashcode * 397) + Message.GetHashCode();
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("UserHistoryDataSet(");
      bool __first = true;
      if (UserID != null && __isset.userID)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("UserID: ");
        sb.Append(UserID);
      }
      if (History != null && __isset.history)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("History: ");
        sb.Append(History);
      }
      if (DiseaseTypes != null && __isset.diseaseTypes)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("DiseaseTypes: ");
        sb.Append(DiseaseTypes);
      }
      if (Message != null && __isset.message)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Message: ");
        sb.Append(Message);
      }
      sb.Append(")");
      return sb.ToString();
    }
  }

}
