/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


namespace vdivsvirus.interfaces
{

  /// <summary>
  /// Structs of PropabilityDataSet [OUTPUT]
  /// </summary>
  public partial class PropabilityDataSet : TBase
  {
    private string _userID;
    private long _time;
    private Dictionary<string, sbyte> _propabilities;

    public string UserID
    {
      get
      {
        return _userID;
      }
      set
      {
        __isset.userID = true;
        this._userID = value;
      }
    }

    public long Time
    {
      get
      {
        return _time;
      }
      set
      {
        __isset.time = true;
        this._time = value;
      }
    }

    public Dictionary<string, sbyte> Propabilities
    {
      get
      {
        return _propabilities;
      }
      set
      {
        __isset.propabilities = true;
        this._propabilities = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool userID;
      public bool time;
      public bool propabilities;
    }

    public PropabilityDataSet()
    {
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                UserID = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I64)
              {
                Time = await iprot.ReadI64Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.Map)
              {
                {
                  TMap _map13 = await iprot.ReadMapBeginAsync(cancellationToken);
                  Propabilities = new Dictionary<string, sbyte>(_map13.Count);
                  for(int _i14 = 0; _i14 < _map13.Count; ++_i14)
                  {
                    string _key15;
                    sbyte _val16;
                    _key15 = await iprot.ReadStringAsync(cancellationToken);
                    _val16 = await iprot.ReadByteAsync(cancellationToken);
                    Propabilities[_key15] = _val16;
                  }
                  await iprot.ReadMapEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("PropabilityDataSet");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if (UserID != null && __isset.userID)
        {
          field.Name = "userID";
          field.Type = TType.String;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(UserID, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (__isset.time)
        {
          field.Name = "time";
          field.Type = TType.I64;
          field.ID = 2;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI64Async(Time, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (Propabilities != null && __isset.propabilities)
        {
          field.Name = "propabilities";
          field.Type = TType.Map;
          field.ID = 3;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          {
            await oprot.WriteMapBeginAsync(new TMap(TType.String, TType.Byte, Propabilities.Count), cancellationToken);
            foreach (string _iter17 in Propabilities.Keys)
            {
              await oprot.WriteStringAsync(_iter17, cancellationToken);
              await oprot.WriteByteAsync(Propabilities[_iter17], cancellationToken);
            }
            await oprot.WriteMapEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      var other = that as PropabilityDataSet;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.userID == other.__isset.userID) && ((!__isset.userID) || (System.Object.Equals(UserID, other.UserID))))
        && ((__isset.time == other.__isset.time) && ((!__isset.time) || (System.Object.Equals(Time, other.Time))))
        && ((__isset.propabilities == other.__isset.propabilities) && ((!__isset.propabilities) || (TCollections.Equals(Propabilities, other.Propabilities))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.userID)
          hashcode = (hashcode * 397) + UserID.GetHashCode();
        if(__isset.time)
          hashcode = (hashcode * 397) + Time.GetHashCode();
        if(__isset.propabilities)
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Propabilities);
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("PropabilityDataSet(");
      bool __first = true;
      if (UserID != null && __isset.userID)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("UserID: ");
        sb.Append(UserID);
      }
      if (__isset.time)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Time: ");
        sb.Append(Time);
      }
      if (Propabilities != null && __isset.propabilities)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Propabilities: ");
        sb.Append(Propabilities);
      }
      sb.Append(")");
      return sb.ToString();
    }
  }

}
