/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace vdivsvirus.interfaces
{
  /// <summary>
  /// Symptome Classifier
  /// none : Keine Symptome Classifizierung (hidden field)
  /// bool : YesNo Frage
  /// scalar : 0 - 5
  /// </summary>
  public enum SymptomeClassifier
  {
    none = 0,
    yesno = 1,
    scalar = 2,
  }
}
